"""Constantes de negocio compartidas por la plataforma psicoeducativa."""

# PHQ-9 (depresión) — rango 0 a 27
PUNTAJE_MAXIMO_PHQ9 = 27
PUNTAJE_RIESGO_SEVERO_PHQ9 = 20
PUNTAJE_RIESGO_MODSEVERO_PHQ9 = 15
PUNTAJE_RIESGO_MODERADO_PHQ9 = 10
PUNTAJE_RIESGO_LEVE_PHQ9 = 5

# GAD-7 (ansiedad) — rango 0 a 21
PUNTAJE_MAXIMO_GAD7 = 21
PUNTAJE_RIESGO_SEVERO_GAD7 = 15
PUNTAJE_RIESGO_MODERADO_GAD7 = 10
PUNTAJE_RIESGO_LEVE_GAD7 = 5

# Ítems
PUNTAJE_MINIMO_ITEM = 0
PUNTAJE_MAXIMO_ITEM = 3
NUM_ITEMS_PHQ9 = 9
NUM_ITEMS_GAD7 = 7

# Estudiantes
EDAD_MINIMA = 16
SEMESTRE_MINIMO = 1
SEMESTRE_MAXIMO = 12
LONGITUD_MINIMA_CODIGO = 4

# Sesiones
HORA_INICIO_ATENCION = 8
HORA_FIN_ATENCION = 18
DURACION_MINIMA_SESION = 15
DURACION_MAX_SESION = 120

# Reglas de negocio
DIAS_MINIMOS_REAPLICACION = 14
DIAS_VENTANA_COMORBILIDAD = 30
