"""Constantes de negocio compartidas por la plataforma psicoeducativa."""

EDAD_MINIMA = 16
SEMESTRE_MINIMO = 1
SEMESTRE_MAXIMO = 12
LONGITUD_MINIMA_CODIGO = 4

NUM_ITEMS_GAD7 = 7
NUM_ITEMS_PHQ9 = 9
PUNTAJE_MINIMO_ITEM = 0
PUNTAJE_MAXIMO_ITEM = 3

PUNTAJE_RIESGO_LEVE_GAD7 = 5
PUNTAJE_RIESGO_MODERADO_GAD7 = 10
PUNTAJE_RIESGO_SEVERO_GAD7 = 15

PUNTAJE_RIESGO_LEVE_PHQ9 = 5
PUNTAJE_RIESGO_MODERADO_PHQ9 = 10
PUNTAJE_RIESGO_MODSEVERO_PHQ9 = 15
PUNTAJE_RIESGO_SEVERO_PHQ9 = 20

DIAS_VENTANA_COMORBILIDAD = 30

HORA_INICIO_ATENCION = 8
HORA_FIN_ATENCION = 18
DURACION_MINIMA_SESION = 15
